### ISSUE TITLE
WarZone and SafeZone

### ISSUE THREAD

**Issue by jopasma7** [nsporillo/HCFactions#14]
Hi, I have some problems when i try to claim safezone and warzone.

Is possible this or not?

I need to claim the /spawn in my HCFactions but I can't claim SafeZone.

Can you help me?

**Comment by nsporillo** [comment]
Yes it is possible to claim safezone and warzone. 

The command is:
> /f claim (radius) (faction)

and an example usage is:
> /f claim 5 safezone
