### ISSUE TITLE
Safezone.

### ISSUE THREAD

**Issue by DirtyDevil69** [nsporillo/HCFactions#3]
I cant seem to join the Safezone Faction or the Warzone Faction to claim land for my spawn or for my other areas. Do you have a fix on that?

**Comment by nsporillo** [comment]
Use `/f claim 1 safezone`

**Comment by DirtyDevil69** [comment]
So how much does that claim?

**Comment by nsporillo** [comment]
1 chunk. 

If you use `/f claim 3 safezone` you claim starting in the chunk you're standing, 3 chunks around. 

![157a07f34db74e7786802857ab7fe107](https://cloud.githubusercontent.com/assets/1480197/17473344/0238ec5c-5d1e-11e6-900d-e40ad56f2a53.png)

![b656aad59c2f4007adc5b89345155d8a](https://cloud.githubusercontent.com/assets/1480197/17473423/71cdc7a4-5d1e-11e6-829a-9e9c0020cb29.png)

The formula is roughly (radius)^3 - 2 chunks.

**Comment by DirtyDevil69** [comment]
Alright, Thank you.

**Comment by DirtyDevil69** [comment]
is it the same thing for warzone as well?

**Comment by nsporillo** [comment]
Yes. You can also unclaim all warzone and safezone with `/f safeunclaimall` and `/f warunclaimall`.

**Comment by DirtyDevil69** [comment]
Thank you.
