### ISSUE TITLE
HcFactions F Who Error.

### ISSUE THREAD

**Issue by BardBuffs** [nsporillo/HCFactions#6]
When I type ./f who I get this error. https://gyazo.com/68ff0a46a0fe71df7920711fe7e28b09 There should be a list of members below where it says allies. Im running paper spigot 1.7.10.  Current plugin list https://gyazo.com/9438501c40afc2126113c0477c7a682b . (if I type f who in chat without the slash the error does not show up however the plugin still does not display the faction members.

**Comment by nsporillo** [comment]
Can you post your config.yml please?

Sorry for the late reply.

**Comment by ItemMeta** [comment]
I'm also having the same problem, even with a default config. 
The error is a NoSuchMethodError.  
net.libhalt.bukkit.flob.killstats.Paraser.getFancY(Paraser.java:37)

**Comment by nsporillo** [comment]
@ItemMeta You're using a third party plugin...

**Comment by ItemMeta** [comment]
I am using https://dev.bukkit.org/bukkit-plugins/hcfactions/

**Comment by ItemMeta** [comment]
The error is with the online, and ally variables.

**Comment by yaboicriminal** [comment]
@ItemMeta you are not using the original factions plugin. You're using a plugin with addons creatd by libhalt. This is why you are getting the NoSuchMethodError exception

**Comment by ItemMeta** [comment]
Where's the original one?
