### ISSUE TITLE
Issue with Java version?

### ISSUE THREAD

**Issue by Cl3mo69** [nsporillo/HCFactions#8]
Hi, i'm in 1.8 spigot version and HCFactions don't run.

**Comment by nsporillo** [comment]
What is the error that you are getting? Link using https://gist.github.com.

**Comment by Cl3mo69** [comment]
As if the plugin was not detected

**Comment by nsporillo** [comment]
You're not supplying sufficient information to provide any assistance. 

Post your start up log

**Comment by Cl3mo69** [comment]
> [20:28:45 ERROR]: Could not load 'plugins/HCFactions.jar' in folder 'plugins'
> org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/massivecraft/factions/P : Unsupported major.minor version 52.0
>         at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-c136710-350cb99]
>         at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-c136710-350cb99]
>         at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-c136710-350cb99]
>         at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugins(CraftServer.java:291) [spigot.jar:git-Spigot-c136710-350cb99]
>         at org.bukkit.craftbukkit.v1_8_R2.CraftServer.reload(CraftServer.java:744) [spigot.jar:git-Spigot-c136710-350cb99]
>         at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigot.jar:git-Spigot-c136710-350cb99]
>         at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-c136710-350cb99]
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-c136710-350cb99]
>         at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-c136710-350cb99]
>         at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot.jar:git-Spigot-c136710-350cb99]
>         at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot.jar:git-Spigot-c136710-350cb99]
>         at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-c136710-350cb99]
>         at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-c136710-350cb99]
>         at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-c136710-350cb99]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_111]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_111]
>         at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-c136710-350cb99]
>         at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-c136710-350cb99]
>         at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-c136710-350cb99]
>         at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-c136710-350cb99]
>         at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-c136710-350cb99]
>         at java.lang.Thread.run(Thread.java:745) [?:1.7.0_111]
> Caused by: java.lang.UnsupportedClassVersionError: com/massivecraft/factions/P : Unsupported major.minor version 52.0
>         at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_111]
>         at java.lang.ClassLoader.defineClass(ClassLoader.java:803) ~[?:1.7.0_111]
>         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_111]
>         at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_111]
>         at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_111]
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_111]
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_111]
>         at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_111]
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_111]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-c136710-350cb99]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-c136710-350cb99]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_111]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_111]
>         at java.lang.Class.forName0(Native Method) ~[?:1.7.0_111]
>         at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_111]
>         at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-c136710-350cb99]
>         at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-c136710-350cb99]
>         ... 21 more

**Comment by nsporillo** [comment]
Posting logs to gists are appreciated.

HCFactions was compiled and built against Java 8. That is, you need to have Java 8 installed in order to run this plugin. Sorry for the inconvenience, but Java 8 has been out since 2014.

**Comment by Cl3mo69** [comment]
Thank's, I'm installing Java 8 on my linux machine
