### ISSUE TITLE
Scoreboard // [Wilder] nametag

### ISSUE THREAD

**Issue by bddvlpr** [nsporillo/HCFactions#9]
Im just here to ask how to disable the scoreboard with 
YourFactions
Power
Dtr
...
on it, and how to disable the Nametags with [Wilder]

**Comment by SoccerPro0813** [comment]
I have the same problem, still trying to fix this.

**Comment by nsporillo** [comment]
In the file "config.yml" set `scoreboard.default-enabled` to false. 

If you'd like to change what the sidebar says, edit the `scoreboard.default` list using the {} variables found at the bottom of the file.
